/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddDevice: typeof import('./src/components/AddDevice/AddDevice.vue')['default']
    AddDevice_cupboard_list: typeof import('./src/components/AddDevice/AddDevice_cupboard_list.vue')['default']
    AddDevice_cupboard_list_box: typeof import('./src/components/AddDevice/AddDevice_cupboard_list_box.vue')['default']
    AddDevice_device_list: typeof import('./src/components/AddDevice/AddDevice_device_list.vue')['default']
    AddSource: typeof import('./src/components/AddSource/AddSource.vue')['default']
    AddSource_cupboard_list: typeof import('./src/components/AddSource/AddSource_cupboard_list.vue')['default']
    AddSource_cupboard_list_box: typeof import('./src/components/AddSource/AddSource_cupboard_list_box.vue')['default']
    AddSource_device_list: typeof import('./src/components/AddSource/AddSource_device_list.vue')['default']
    AddSource_sources_list: typeof import('./src/components/AddSource/AddSource_sources_list.vue')['default']
    ApplySource: typeof import('./src/components/ApplySource.vue')['default']
    AuthorityWindows: typeof import('./src/components/Register/AuthorityWindows.vue')['default']
    CardWindows: typeof import('./src/components/Register/CardWindows.vue')['default']
    CupBoard: typeof import('./src/components/cupBoard.vue')['default']
    CupBox: typeof import('./src/components/cupBox.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    FindWhoUsingSource: typeof import('./src/components/FindWhoUsingSource.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    PasswordWindows: typeof import('./src/components/Register/PasswordWindows.vue')['default']
    ProcessCard: typeof import('./src/components/ProcessCard.vue')['default']
    ProcessList: typeof import('./src/components/ProcessList.vue')['default']
    Register: typeof import('./src/components/Register/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectSource: typeof import('./src/components/SelectSource.vue')['default']
    SourceCard: typeof import('./src/components/SourceCard.vue')['default']
    SourceList: typeof import('./src/components/SourceList.vue')['default']
    SQLListViewer: typeof import('./src/components/SQLListViewer.vue')['default']
    ThemeSwitcher: typeof import('./src/components/themeSwitcher.vue')['default']
    TmpChart: typeof import('./src/components/DashBoard/TmpChart.vue')['default']
    TmpEcharts: typeof import('./src/components/DashBoard/TmpEcharts.vue')['default']
    TmpNet: typeof import('./src/components/DashBoard/TmpNet.vue')['default']
    TmpSafeCode: typeof import('./src/components/TmpSafeCode.vue')['default']
    TmpTCP: typeof import('./src/components/DashBoard/TmpTCP.vue')['default']
    ToolbarNotifications: typeof import('./src/components/tmp/ToolbarNotifications.vue')['default']
    UserInfoCard: typeof import('./src/components/UserInfoCard.vue')['default']
    UserWindows: typeof import('./src/components/Register/UserWindows.vue')['default']
  }
}
